### ISSUE TITLE
Error: Function not implemented

### ISSUE THREAD

**Issue by raduvarga** [neurio/react-native-local-network-permission#7]
Getting `Error: Function not implemented.` when calling any of the 2 functions.

Running react-native 0.71.7

**Comment by benjaminkomen** [comment]
Hi @raduvarga, thanks for raising this issue. Can you please provide a minimal reproducible example?

**Comment by raduvarga** [comment]
@benjaminkomen Sorry, that was a silly mistake on my part, I wasn't importing the functions properly.

Now that it's imported properly, I am getting this error:

`Cannot find native module 'ReactNativeLocalNetworkPermission'

Does this have something to do with the linking?
The version I'm using is 1.1.0.

There is also a `The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is linked properly` warning, but I am not using Expo.

**Comment by benjaminkomen** [comment]
@raduvarga , right, this library is mainly designed to work with Expo. If you use a bare react native project, you need to follow some steps first, you can read more how to do this here: https://docs.expo.dev/bare/installing-expo-modules/
