### ISSUE TITLE
Cannot find native module ReactNativeLocalNetworkPermission

### ISSUE THREAD

**Issue by Kevinhellomove** [neurio/react-native-local-network-permission#8]
The library works fine on android but crash on ios displaying this error Cannot find native module ReactNativeLocalNetworkPermission @benjaminkomen

**Comment by benjaminkomen** [comment]
This library is specifically meant for iOS, not Android.
Can you provide a minimum reproducible example?

**Comment by Kevinhellomove** [comment]
I simply follow the documentation, import the library and call the function.
  async function checkLocalNetwork()
  {
    const request = await requestLocalNetworkAccess();
    const result = await checkLocalNetworkAccess();

    console.log(request,result)
  }

  useEffect(()=>{
    checkLocalNetwork()
  },[])

On android return undefined and true on ios return Cannot find native module ReactNativeLocalNetworkPermission im using expo and traying in expo go @benjaminkomen

**Comment by benjaminkomen** [comment]
You cannot directly use this library in Expo Go, you need to [create a development build](https://docs.expo.dev/develop/development-builds/create-a-build/) because the native code in this library.

**Comment by Kevinhellomove** [comment]
ok, thank you i will try.
